### ISSUE TITLE
launcher stuck waiting on auth pop-up

### ISSUE THREAD

**Issue by pokemane** [MOONMOONOSS/HeliosLauncher#63]
Launcher is stuck waiting on the auth popup even though I already went through it. 

I signed in with MC creds, clicked "link with Discord". I used the QR code to link. I clicked the "accept" button on my phone after I scanned the code.

This is where it's stuck:

![image](https://user-images.githubusercontent.com/1995662/89482352-afd81a00-d767-11ea-9eb7-61395d05c65e.png)

ctrl + R brings me back here after the moon logo:

![image](https://user-images.githubusercontent.com/1995662/89482380-c1212680-d767-11ea-9d85-47d3812ec789.png)

And here's the console output:

![image](https://user-images.githubusercontent.com/1995662/89482405-d433f680-d767-11ea-87bb-a03383b3300f.png)

At Dunk's suggestion, I ran the launcher directly from the exe to get the IPC output:

```
PS E:\minecraft\mooncord\MOON2 Launcher - 720456198435897386\content>
Requesting auth code from Discord...
Awaiting Discord user approval
(node:9384) UnhandledPromiseRejectionWarning: FetchError: network timeout at: https://panel.moonmoon.live:8000/v1/login
    at Timeout.<anonymous> (E:\minecraft\mooncord\MOON2 Launcher - 720456198435897386\content\resources\app.asar\node_modules\node-fetch\lib\index.js:1448:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:9384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pokemane** [comment]
Checked my pfsense logs for anything from `moonmoon.live`, didn't see anything. Checked the `moonmoon.live` cert too, but it's still good for now and I can get to the url that "timed out" just fine in my browser. It 404s but at least it's there and not blocked, which agrees with me not seeing anything in my firewall logs.

Checked my system event logs, found this a few seconds after I clicked through the auth popup:

```
Name resolution for the name panel.moonmoon.live timed out after none of the configured DNS servers responded.
```

This event popped up after a couple dcom events with the same message, the first of which aligns closer with the actual launcher event:

```
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID
<etc etc etc>
```

Unsure if this is a "fixed by running as admin" or if I've actually got to go mess with dcom settings/regkeys. I'm on win 10.0.18363. It's running in KVM but I don't think that should matter.

I'll try uninstalling and reinstalling on the "root disk" to see if that makes it happier. Some other applications have gotten cranky at me when I install them on the other (directly passed-through instead of vdisk) drive so I'll check that first.

**Comment by pokemane** [comment]
More info/testing: Installing on other drive didn't help. Nuking the `%appdata%\moonmoon-launcher` folder to get rid of cookies and stuff let me go back through the auth process and sign in with my minecraft creds, but still no dice. Stuck at the same spot. Running as admin also didn't help.
